# permissions for end users to view occronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: occronjob-viewer-role
rules:
- apiGroups:
  - executers.ibm-csm.com
  resources:
  - occronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - executers.ibm-csm.com
  resources:
  - occronjobs/status
  verbs:
  - get
